import "~/styles/globals.css";

import { Assistant } from "next/font/google";
import AuthProvider from "~/components/auth/auth-provider";
import FooterNavBar from "~/components/footer/footer-nav-bar";
import NavBar from "~/components/header/nav-bar";

const assistant = Assistant({
  subsets: ["hebrew"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="he">
      <body
        dir="rtl"
        className={`flex min-h-screen flex-col font-sans ${assistant.variable}`}
      >
        <AuthProvider>
          <header className="border-b-2 border-b-zinc-50 shadow-md">
            <NavBar />
          </header>
          <main className="h-full flex-grow">{children}</main>
          <footer className="mt-auto w-full justify-end bg-zinc-900 p-8 text-white md:px-8 lg:px-12">
            <FooterNavBar />
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
